# Generated by Django 4.0.3 on 2022-03-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_categories_subcategories_freelancerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.categories'),
        ),
    ]
