# Generated by Django 4.0.3 on 2022-03-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_companydetails_employerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='profile',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.employerprofile'),
            preserve_default=False,
        ),
    ]
