# Generated by Django 4.0.3 on 2022-03-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
