# Generated by Django 4.0.3 on 2022-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_employerprofile_first_name_employerprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
