# Generated by Django 4.0.3 on 2022-03-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_freelancerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
