# Generated by Django 4.0.3 on 2022-04-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_freelancerprofile_programming_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
