# Generated by Django 4.0.3 on 2022-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfeedback',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
